spring:
  application:
    name: service-c
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: true
        root: dev
        metadata:
          versions: 1,2

server:
  port: 10101